"""Adaptive NBF attack — paper-strict selector.

Paper reference: NBF paper Sec. B.2 / Table 14.

    "Adaptive attack (B.2, Table 14): each attack query is still generated
    by Crescendo, but among candidates, the one chosen is the WORST-CASE
    for the defense: sample 3 candidate queries empirically per turn and
    pick the one maximizing the NBF value h(x_{k-1}, u) under the current
    state."

What is specified in the NBF paper:
    - Default base attack: Crescendo
    - Number of candidates per turn: 3
    - Selection rule: argmax over h(x_{k-1}, u)
    - "Empirical sampling" of the 3 candidate queries

What is NOT specified in the NBF paper:
    - The exact form of "empirical sampling" (3 calls to base_attack vs.
      3 perturbed copies vs. 3 paraphrases — paper does not say).  We
      implement the most direct reading: 3 independent calls to
      ``base_attack.next_query(goal, history)``.  Deterministic base
      attacks will therefore yield 3 identical candidates; the paper
      implicitly assumes a non-deterministic base.  Swap the base attack
      for the official Russinovich et al. 2024 implementation to match
      the paper's evaluation.

The adaptive attack never writes to the NBF model or to the steered
chat's state.  It only reads ``current_state`` and ``h(...)``.
"""
from __future__ import annotations

from typing import Callable

import torch

from ..logging_utils import get_logger
from ..schemas import Turn
from .base import MultiTurnAttack
from .crescendo import CrescendoAttack

logger = get_logger(__name__)


NUM_CANDIDATES = 3  # paper B.2: 3 candidate queries per turn


class AdaptiveNBFAttack(MultiTurnAttack):
    """Worst-case query selector: argmax over h(x, u_candidate).

    Paper-strict selector.  The 3 candidates are generated by calling
    ``base_attack.next_query(goal, history)`` three times.  This is the
    most direct reading of the paper's "sample 3 candidate queries
    empirically" wording; the official Crescendo implementation (when
    pasted into ``crescendo.py``) is the expected base.
    """

    name = "adaptive"

    def __init__(
        self,
        base_attack: MultiTurnAttack | None = None,
        embed_fn: Callable[[str], torch.Tensor] | None = None,
        barrier=None,
        state_fn: Callable[[], torch.Tensor] | None = None,
        num_candidates: int = NUM_CANDIDATES,
    ):
        self.base_attack = base_attack if base_attack is not None else CrescendoAttack()
        self.embed_fn = embed_fn
        self.barrier = barrier
        self.state_fn = state_fn
        self.num_candidates = num_candidates

    @property
    def label(self) -> str:
        return f"adaptive_{self.base_attack.name}"

    def next_query(self, goal: str, history: list[Turn]) -> str:
        """Pick the argmax-h candidate from ``num_candidates`` samples.

        1. Sample ``num_candidates`` candidate queries from the base
           attack (3 independent calls with the same history).
        2. Embed each candidate.
        3. Evaluate h(x_current, u_candidate) under no_grad.
        4. Return the candidate with the maximum h (worst case).
        """
        raw_candidates: list[str] = []
        for _ in range(self.num_candidates):
            q = self.base_attack.next_query(goal, history)
            if q and q.strip():
                raw_candidates.append(q)

        if not raw_candidates:
            return self.base_attack.next_query(goal, history)

        if self.embed_fn is None or self.barrier is None or self.state_fn is None:
            return raw_candidates[0]

        state = self.state_fn()
        if state.dim() == 1:
            state = state.unsqueeze(0)

        h_values: list[float] = []
        for cand in raw_candidates:
            u = self.embed_fn(cand)
            if u.dim() == 1:
                u = u.unsqueeze(0)
            u = u.to(state.device)
            with torch.no_grad():
                h_val = self.barrier.h(state, u)
            h_values.append(float(h_val.detach().cpu().reshape(-1)[0].item()))

        best_idx = max(range(len(h_values)), key=lambda i: h_values[i])
        selected = raw_candidates[best_idx]

        logger.debug(
            "Adaptive[%s] h=%s selected=%d (h=%.4f)",
            self.base_attack.name,
            [f"{h:.4f}" for h in h_values],
            best_idx,
            h_values[best_idx],
        )
        return selected

    def is_finished(self, history: list[Turn], max_turns: int = 8) -> bool:
        return len(history) >= max_turns
